/* prettier-ignore */
/**
 * WARNING: This file is auto-generated by Convex and should not be edited directly.
 */

import type { ApiFromModules } from "convex/server";
import * as mutations from "../mutations";

/**
 * A type describing the shape of the Convex API.
 */
export type API = ApiFromModules<{
  mutations: typeof mutations;
}>;

export const api = null as unknown as {
  mutations: {
    getTasks: {
      (_: any): Promise<any>;
    };
    getTask: {
      (_: { taskId: any }): Promise<any>;
    };
    getTaskMessages: {
      (_: { taskId: any }): Promise<any[]>;
    };
    getActivities: {
      (_: any): Promise<any[]>;
    };
    getAgents: {
      (_: any): Promise<any[]>;
    };
    getAgentNotifications: {
      (_: { agentId: any }): Promise<any[]>;
    };
    createTask: {
      (_: {
        title: string;
        description: string;
        assigneeIds?: any[];
        dueDate?: number;
      }): Promise<any>;
    };
    updateTaskStatus: {
      (_: {
        taskId: any;
        status: "inbox" | "assigned" | "in_progress" | "review" | "done" | "blocked";
      }): Promise<void>;
    };
    assignTask: {
      (_: { taskId: any; agentIds: any[] }): Promise<void>;
    };
    postMessage: {
      (_: {
        taskId: any;
        fromAgentId: any;
        content: string;
        attachments?: any[];
      }): Promise<any>;
    };
    createDocument: {
      (_: {
        title: string;
        content: string;
        type: "deliverable" | "research" | "protocol" | "notes";
        taskId?: any;
        createdBy: any;
      }): Promise<any>;
    };
    agentHeartbeat: {
      (_: { agentId: any }): Promise<void>;
    };
    markNotificationDelivered: {
      (_: { notificationId: any }): Promise<void>;
    };
  };
};
