/* prettier-ignore */
/**
 * WARNING: This file is auto-generated by Convex and should not be edited directly.
 */

import type { ApiFromModules } from "convex/server";
import * as mutations from "../mutations";

/**
 * A type describing the shape of the Convex API.
 */
export type API = ApiFromModules<{
  mutations: typeof mutations;
}>;

export const api = {
  mutations: {
    // Workspaces
    getWorkspaces: { _type: 'query' } as any,
    getWorkspace: { _type: 'query' } as any,
    createWorkspace: { _type: 'mutation' } as any,

    // Agents
    getWorkspaceAgents: { _type: 'query' } as any,
    createAgent: { _type: 'mutation' } as any,
    updateAgentStatus: { _type: 'mutation' } as any,
    agentHeartbeat: { _type: 'mutation' } as any,

    // Tasks
    getWorkspaceTasks: { _type: 'query' } as any,
    getTask: { _type: 'query' } as any,
    createTask: { _type: 'mutation' } as any,
    updateTaskStatus: { _type: 'mutation' } as any,
    assignTask: { _type: 'mutation' } as any,

    // Messages
    getConversationMessages: { _type: 'query' } as any,
    getTaskConversation: { _type: 'query' } as any,
    postMessage: { _type: 'mutation' } as any,

    // Activities
    getWorkspaceActivities: { _type: 'query' } as any,

    // Notifications
    getAgentNotifications: { _type: 'query' } as any,
    markNotificationDelivered: { _type: 'mutation' } as any,
  },
} as any;
