/* prettier-ignore */
/**
 * WARNING: This file is auto-generated by Convex and should not be edited directly.
 */

import type { ApiFromModules } from "convex/server";
import * as mutations from "../mutations";

/**
 * A type describing the shape of the Convex API.
 */
export type API = ApiFromModules<{
  mutations: typeof mutations;
}>;

export const api = null as unknown as {
  mutations: {
    // Workspaces
    getWorkspaces: { (_: any): Promise<any[]> };
    getWorkspace: { (_: { workspaceId: any }): Promise<any> };
    createWorkspace: { (_: { name: string; description?: string }): Promise<any> };

    // Agents
    getWorkspaceAgents: { (_: { workspaceId: any }): Promise<any[]> };
    createAgent: { (_: any): Promise<any> };
    updateAgentStatus: { (_: any): Promise<void> };
    agentHeartbeat: { (_: { agentId: any }): Promise<void> };

    // Tasks
    getWorkspaceTasks: { (_: { workspaceId: any }): Promise<any[]> };
    getTask: { (_: { taskId: any }): Promise<any> };
    createTask: { (_: any): Promise<any> };
    updateTaskStatus: { (_: any): Promise<void> };
    assignTask: { (_: any): Promise<void> };

    // Messages
    getConversationMessages: { (_: { conversationId: any }): Promise<any[]> };
    getTaskConversation: { (_: { taskId: any }): Promise<any> };
    postMessage: { (_: any): Promise<any> };

    // Activities
    getWorkspaceActivities: { (_: { workspaceId: any }): Promise<any[]> };

    // Notifications
    getAgentNotifications: { (_: { agentId: any }): Promise<any[]> };
    markNotificationDelivered: { (_: { notificationId: any }): Promise<void> };
  };
};
