/* prettier-ignore */
/**
 * WARNING: This file is auto-generated by Convex and should not be edited directly.
 * Instead, modify the functions in convex/ directory and run `convex dev`
 */

import { ConvexClient } from "convex/browser";

const convexUrl = process.env.NEXT_PUBLIC_CONVEX_URL;
if (!convexUrl) {
  throw new Error("NEXT_PUBLIC_CONVEX_URL environment variable is not set");
}

export const convex = new ConvexClient(convexUrl);
