/* prettier-ignore */
/**
 * WARNING: This file is auto-generated by Convex and should not be edited directly.
 * Instead, modify the functions in convex/ directory and run `convex dev`
 */

import { defineSchema, defineTable } from "convex/server";

export const mutation = (config: any) => config;
export const query = (config: any) => config;
export const action = (config: any) => config;
